// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// The current database to use.
use('FIFA2022');

// Create a new document in the collection.
db.getCollection('TeamsData').insertMany(
    [
        {
          "team": "Argentina",
          "players_used": 24,
          "avg_age": 28.4,
          "possession": 57.4,
          "games": 7,
          "games_starts": 77,
          "minutes": 690,
          "minutes_90s": 7.7,
          "goals": 15,
          "assists": 8,
          "goals_pens": 11,
          "pens_made": 4,
          "pens_att": 5,
          "cards_yellow": 17,
          "cards_red": 0,
          "goals_per90": 1.96,
          "assists_per90": 1.04,
          "goals_assists_per90": 3,
          "goals_pens_per90": 1.43,
          "goals_assists_pens_per90": 2.48,
          "xg": 15.2
        },
        {
          "team": "Australia",
          "players_used": 20,
          "avg_age": 28.7,
          "possession": 37.8,
          "games": 4,
          "games_starts": 44,
          "minutes": 360,
          "minutes_90s": 4,
          "goals": 3,
          "assists": 3,
          "goals_pens": 3,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 7,
          "cards_red": 0,
          "goals_per90": 0.75,
          "assists_per90": 0.75,
          "goals_assists_per90": 1.5,
          "goals_pens_per90": 0.75,
          "goals_assists_pens_per90": 1.5,
          "xg": 2.3
        },
        {
          "team": "Belgium",
          "players_used": 20,
          "avg_age": 30.6,
          "possession": 57,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 1,
          "assists": 1,
          "goals_pens": 1,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 5,
          "cards_red": 0,
          "goals_per90": 0.33,
          "assists_per90": 0.33,
          "goals_assists_per90": 0.67,
          "goals_pens_per90": 0.33,
          "goals_assists_pens_per90": 0.67,
          "xg": 4.7
        },
        {
          "team": "Brazil",
          "players_used": 26,
          "avg_age": 28.5,
          "possession": 56.2,
          "games": 5,
          "games_starts": 55,
          "minutes": 480,
          "minutes_90s": 5.3,
          "goals": 8,
          "assists": 6,
          "goals_pens": 7,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 6,
          "cards_red": 0,
          "goals_per90": 1.5,
          "assists_per90": 1.13,
          "goals_assists_per90": 2.62,
          "goals_pens_per90": 1.31,
          "goals_assists_pens_per90": 2.44,
          "xg": 12
        },
        {
          "team": "Cameroon",
          "players_used": 22,
          "avg_age": 28,
          "possession": 41.7,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 4,
          "assists": 4,
          "goals_pens": 4,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 8,
          "cards_red": 1,
          "goals_per90": 1.33,
          "assists_per90": 1.33,
          "goals_assists_per90": 2.67,
          "goals_pens_per90": 1.33,
          "goals_assists_pens_per90": 2.67,
          "xg": 3.4
        },
        {
          "team": "Canada",
          "players_used": 19,
          "avg_age": 28.2,
          "possession": 52,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 1,
          "assists": 1,
          "goals_pens": 1,
          "pens_made": 0,
          "pens_att": 1,
          "cards_yellow": 8,
          "cards_red": 0,
          "goals_per90": 0.33,
          "assists_per90": 0.33,
          "goals_assists_per90": 0.67,
          "goals_pens_per90": 0.33,
          "goals_assists_pens_per90": 0.67,
          "xg": 4.2
        },
        {
          "team": "Costa Rica",
          "players_used": 22,
          "avg_age": 30.6,
          "possession": 31.3,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 3,
          "assists": 1,
          "goals_pens": 3,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 6,
          "cards_red": 0,
          "goals_per90": 1,
          "assists_per90": 0.33,
          "goals_assists_per90": 1.33,
          "goals_pens_per90": 1,
          "goals_assists_pens_per90": 1.33,
          "xg": 1.4
        },
        {
          "team": "Croatia",
          "players_used": 21,
          "avg_age": 29.2,
          "possession": 54.3,
          "games": 7,
          "games_starts": 77,
          "minutes": 690,
          "minutes_90s": 7.7,
          "goals": 8,
          "assists": 8,
          "goals_pens": 8,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 8,
          "cards_red": 0,
          "goals_per90": 1.04,
          "assists_per90": 1.04,
          "goals_assists_per90": 2.09,
          "goals_pens_per90": 1.04,
          "goals_assists_pens_per90": 2.09,
          "xg": 7
        },
        {
          "team": "Denmark",
          "players_used": 20,
          "avg_age": 27.5,
          "possession": 60,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 1,
          "assists": 1,
          "goals_pens": 1,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 5,
          "cards_red": 0,
          "goals_per90": 0.33,
          "assists_per90": 0.33,
          "goals_assists_per90": 0.67,
          "goals_pens_per90": 0.33,
          "goals_assists_pens_per90": 0.67,
          "xg": 2.7
        },
        {
          "team": "Ecuador",
          "players_used": 18,
          "avg_age": 25.8,
          "possession": 53.3,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 4,
          "assists": 2,
          "goals_pens": 3,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 3,
          "cards_red": 0,
          "goals_per90": 1.33,
          "assists_per90": 0.67,
          "goals_assists_per90": 2,
          "goals_pens_per90": 1,
          "goals_assists_pens_per90": 1.67,
          "xg": 3
        },
        {
          "team": "England",
          "players_used": 20,
          "avg_age": 27,
          "possession": 62.8,
          "games": 5,
          "games_starts": 55,
          "minutes": 450,
          "minutes_90s": 5,
          "goals": 13,
          "assists": 11,
          "goals_pens": 12,
          "pens_made": 1,
          "pens_att": 2,
          "cards_yellow": 1,
          "cards_red": 0,
          "goals_per90": 2.6,
          "assists_per90": 2.2,
          "goals_assists_per90": 4.8,
          "goals_pens_per90": 2.4,
          "goals_assists_pens_per90": 4.6,
          "xg": 8.7
        },
        {
          "team": "France",
          "players_used": 24,
          "avg_age": 27.2,
          "possession": 51.3,
          "games": 7,
          "games_starts": 77,
          "minutes": 660,
          "minutes_90s": 7.3,
          "goals": 16,
          "assists": 12,
          "goals_pens": 14,
          "pens_made": 2,
          "pens_att": 2,
          "cards_yellow": 8,
          "cards_red": 0,
          "goals_per90": 2.18,
          "assists_per90": 1.64,
          "goals_assists_per90": 3.82,
          "goals_pens_per90": 1.91,
          "goals_assists_pens_per90": 3.55,
          "xg": 13.8
        },
        {
          "team": "Germany",
          "players_used": 20,
          "avg_age": 28.1,
          "possession": 59.3,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 6,
          "assists": 5,
          "goals_pens": 5,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 3,
          "cards_red": 0,
          "goals_per90": 2,
          "assists_per90": 1.67,
          "goals_assists_per90": 3.67,
          "goals_pens_per90": 1.67,
          "goals_assists_pens_per90": 3.33,
          "xg": 10.1
        },
        {
          "team": "Ghana",
          "players_used": 20,
          "avg_age": 26.4,
          "possession": 42,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 5,
          "assists": 2,
          "goals_pens": 5,
          "pens_made": 0,
          "pens_att": 1,
          "cards_yellow": 8,
          "cards_red": 0,
          "goals_per90": 1.67,
          "assists_per90": 0.67,
          "goals_assists_per90": 2.33,
          "goals_pens_per90": 1.67,
          "goals_assists_pens_per90": 2.33,
          "xg": 4.1
        },
        {
          "team": "Iran",
          "players_used": 21,
          "avg_age": 29.3,
          "possession": 36.7,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 4,
          "assists": 2,
          "goals_pens": 3,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 7,
          "cards_red": 0,
          "goals_per90": 1.33,
          "assists_per90": 0.67,
          "goals_assists_per90": 2,
          "goals_pens_per90": 1,
          "goals_assists_pens_per90": 1.67,
          "xg": 3.2
        },
        {
          "team": "Japan",
          "players_used": 22,
          "avg_age": 28.8,
          "possession": 35.8,
          "games": 4,
          "games_starts": 44,
          "minutes": 390,
          "minutes_90s": 4.3,
          "goals": 5,
          "assists": 4,
          "goals_pens": 5,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 6,
          "cards_red": 0,
          "goals_per90": 1.15,
          "assists_per90": 0.92,
          "goals_assists_per90": 2.08,
          "goals_pens_per90": 1.15,
          "goals_assists_pens_per90": 2.08,
          "xg": 5
        },
        {
          "team": "Korea Republic",
          "players_used": 21,
          "avg_age": 29,
          "possession": 48.3,
          "games": 4,
          "games_starts": 44,
          "minutes": 360,
          "minutes_90s": 4,
          "goals": 5,
          "assists": 3,
          "goals_pens": 5,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 6,
          "cards_red": 0,
          "goals_per90": 1.25,
          "assists_per90": 0.75,
          "goals_assists_per90": 2,
          "goals_pens_per90": 1.25,
          "goals_assists_pens_per90": 2,
          "xg": 4.6
        },
        {
          "team": "Mexico",
          "players_used": 21,
          "avg_age": 29,
          "possession": 54,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 2,
          "assists": 1,
          "goals_pens": 2,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 7,
          "cards_red": 0,
          "goals_per90": 0.67,
          "assists_per90": 0.33,
          "goals_assists_per90": 1,
          "goals_pens_per90": 0.67,
          "goals_assists_pens_per90": 1,
          "xg": 3.3
        },
        {
          "team": "Morocco",
          "players_used": 25,
          "avg_age": 27.2,
          "possession": 39,
          "games": 7,
          "games_starts": 77,
          "minutes": 660,
          "minutes_90s": 7.3,
          "goals": 6,
          "assists": 4,
          "goals_pens": 6,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 9,
          "cards_red": 1,
          "goals_per90": 0.82,
          "assists_per90": 0.55,
          "goals_assists_per90": 1.36,
          "goals_pens_per90": 0.82,
          "goals_assists_pens_per90": 1.36,
          "xg": 6.6
        },
        {
          "team": "Netherlands",
          "players_used": 21,
          "avg_age": 27.6,
          "possession": 53,
          "games": 5,
          "games_starts": 55,
          "minutes": 480,
          "minutes_90s": 5.3,
          "goals": 10,
          "assists": 8,
          "goals_pens": 10,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 12,
          "cards_red": 1,
          "goals_per90": 1.87,
          "assists_per90": 1.5,
          "goals_assists_per90": 3.38,
          "goals_pens_per90": 1.87,
          "goals_assists_pens_per90": 3.38,
          "xg": 4.6
        },
        {
          "team": "Poland",
          "players_used": 21,
          "avg_age": 28.7,
          "possession": 37.3,
          "games": 4,
          "games_starts": 44,
          "minutes": 360,
          "minutes_90s": 4,
          "goals": 3,
          "assists": 1,
          "goals_pens": 2,
          "pens_made": 1,
          "pens_att": 2,
          "cards_yellow": 7,
          "cards_red": 0,
          "goals_per90": 0.75,
          "assists_per90": 0.25,
          "goals_assists_per90": 1,
          "goals_pens_per90": 0.5,
          "goals_assists_pens_per90": 0.75,
          "xg": 4.5
        },
        {
          "team": "Portugal",
          "players_used": 24,
          "avg_age": 27.8,
          "possession": 60.4,
          "games": 5,
          "games_starts": 55,
          "minutes": 450,
          "minutes_90s": 5,
          "goals": 12,
          "assists": 10,
          "goals_pens": 10,
          "pens_made": 2,
          "pens_att": 2,
          "cards_yellow": 6,
          "cards_red": 0,
          "goals_per90": 2.4,
          "assists_per90": 2,
          "goals_assists_per90": 4.4,
          "goals_pens_per90": 2,
          "goals_assists_pens_per90": 4,
          "xg": 7.8
        },
        {
          "team": "Qatar",
          "players_used": 20,
          "avg_age": 29,
          "possession": 43,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 1,
          "assists": 1,
          "goals_pens": 1,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 7,
          "cards_red": 0,
          "goals_per90": 0.33,
          "assists_per90": 0.33,
          "goals_assists_per90": 0.67,
          "goals_pens_per90": 0.33,
          "goals_assists_pens_per90": 0.67,
          "xg": 1.4
        },
        {
          "team": "Saudi Arabia",
          "players_used": 23,
          "avg_age": 28.1,
          "possession": 44.7,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 3,
          "assists": 2,
          "goals_pens": 3,
          "pens_made": 0,
          "pens_att": 1,
          "cards_yellow": 14,
          "cards_red": 0,
          "goals_per90": 1,
          "assists_per90": 0.67,
          "goals_assists_per90": 1.67,
          "goals_pens_per90": 1,
          "goals_assists_pens_per90": 1.67,
          "xg": 3
        },
        {
          "team": "Senegal",
          "players_used": 20,
          "avg_age": 27.7,
          "possession": 44.8,
          "games": 4,
          "games_starts": 44,
          "minutes": 360,
          "minutes_90s": 4,
          "goals": 5,
          "assists": 2,
          "goals_pens": 4,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 7,
          "cards_red": 0,
          "goals_per90": 1.25,
          "assists_per90": 0.5,
          "goals_assists_per90": 1.75,
          "goals_pens_per90": 1,
          "goals_assists_pens_per90": 1.5,
          "xg": 4.6
        },
        {
          "team": "Serbia",
          "players_used": 22,
          "avg_age": 27.4,
          "possession": 51.3,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 5,
          "assists": 4,
          "goals_pens": 5,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 12,
          "cards_red": 0,
          "goals_per90": 1.67,
          "assists_per90": 1.33,
          "goals_assists_per90": 3,
          "goals_pens_per90": 1.67,
          "goals_assists_pens_per90": 3,
          "xg": 3.4
        },
        {
          "team": "Spain",
          "players_used": 21,
          "avg_age": 26.4,
          "possession": 75.8,
          "games": 4,
          "games_starts": 44,
          "minutes": 390,
          "minutes_90s": 4.3,
          "goals": 9,
          "assists": 5,
          "goals_pens": 8,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 2,
          "cards_red": 0,
          "goals_per90": 2.08,
          "assists_per90": 1.15,
          "goals_assists_per90": 3.23,
          "goals_pens_per90": 1.85,
          "goals_assists_pens_per90": 3,
          "xg": 6.2
        },
        {
          "team": "Switzerland",
          "players_used": 24,
          "avg_age": 28.5,
          "possession": 49,
          "games": 4,
          "games_starts": 44,
          "minutes": 360,
          "minutes_90s": 4,
          "goals": 5,
          "assists": 4,
          "goals_pens": 5,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 9,
          "cards_red": 0,
          "goals_per90": 1.25,
          "assists_per90": 1,
          "goals_assists_per90": 2.25,
          "goals_pens_per90": 1.25,
          "goals_assists_pens_per90": 2.25,
          "xg": 5.6
        },
        {
          "team": "Tunisia",
          "players_used": 21,
          "avg_age": 27.7,
          "possession": 44.3,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 1,
          "assists": 1,
          "goals_pens": 1,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 5,
          "cards_red": 0,
          "goals_per90": 0.33,
          "assists_per90": 0.33,
          "goals_assists_per90": 0.67,
          "goals_pens_per90": 0.33,
          "goals_assists_pens_per90": 0.67,
          "xg": 2.3
        },
        {
          "team": "United States",
          "players_used": 20,
          "avg_age": 25.4,
          "possession": 53,
          "games": 4,
          "games_starts": 44,
          "minutes": 360,
          "minutes_90s": 4,
          "goals": 3,
          "assists": 3,
          "goals_pens": 3,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 5,
          "cards_red": 0,
          "goals_per90": 0.75,
          "assists_per90": 0.75,
          "goals_assists_per90": 1.5,
          "goals_pens_per90": 0.75,
          "goals_assists_pens_per90": 1.5,
          "xg": 4.1
        },
        {
          "team": "Uruguay",
          "players_used": 19,
          "avg_age": 28.5,
          "possession": 48.7,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 2,
          "assists": 1,
          "goals_pens": 2,
          "pens_made": 0,
          "pens_att": 0,
          "cards_yellow": 8,
          "cards_red": 0,
          "goals_per90": 0.67,
          "assists_per90": 0.33,
          "goals_assists_per90": 1,
          "goals_pens_per90": 0.67,
          "goals_assists_pens_per90": 1,
          "xg": 3.7
        },
        {
          "team": "Wales",
          "players_used": 18,
          "avg_age": 27.7,
          "possession": 46.7,
          "games": 3,
          "games_starts": 33,
          "minutes": 270,
          "minutes_90s": 3,
          "goals": 1,
          "assists": 0,
          "goals_pens": 0,
          "pens_made": 1,
          "pens_att": 1,
          "cards_yellow": 5,
          "cards_red": 1,
          "goals_per90": 0.33,
          "assists_per90": 0,
          "goals_assists_per90": 0.33,
          "goals_pens_per90": 0,
          "goals_assists_pens_per90": 0,
          "xg": 2.7
        }
      ]
  
    
);
